### ISSUE TITLE
WIP: setup-script.sh not working

### ISSUE THREAD

**Issue by FourElements** [memsql/singlestore-kafka-connector#5]
Hello,

Attempted to run setup-script.sh which is in the demo folder but it fails on step "Copying 'singlestore-kafka-connector'..."
Performed some debugging and realized that in the previous step "Building project (this may take some time)...", builds a jar with version 1.0.1, whereas it attempts to copy version 1.0.0 and therefore failing here:
**docker exec singlestore-kafka-connect cp /home/app/target/singlestore-kafka-connector-1.0.0.jar /tmp/quickstart/connect
docker cp /tmp/quickstart/connect/singlestore-kafka-connector-1.0.0.jar kafka-connect:/usr/share/java/kafka**

Altered to:
 **docker exec singlestore-kafka-connect cp /home/app/target/singlestore-kafka-connector-1.0.0.jar /tmp/quickstart/connect
docker cp /tmp/quickstart/connect/singlestore-kafka-connector-1.0.0.jar kafka-connect:/usr/share/java/kafka** 
and performs the step successfully. 

After that, in step "Starting 'singlestore-kafka' docker container...", also fails, due to the ROOT_PASSWORD not being provided.
By checking this documentation: https://docs.singlestore.com/v7.3/guides/deploy-memsql/self-managed/docker/step-2/
passed the required parameter, such as:
docker run -i --init \
    --name singlestore-kafka \
    -e LICENSE_KEY="$LICENSE_KEY" \
    **-e ROOT_PASSWORD="$ROOT_PASSWORD"** \
    -p 3306:3306 -p 8080:8080 \
    --net=confluent \
    memsql/cluster-in-a-box >/dev/null

Now it bootstraps successfully and can even access the console in port 8080.

Although in the following step, can't seem to figure out why and would require help. In this step stays completely stuck:
```
singlestore-wait-start() {
  echo -n "Waiting for SingleStore to start..."
  while true; do
      if docker exec singlestore-kafka memsql -e "select 1" >/dev/null 2>/dev/null; then
          break
      fi
      echo -n "."
      sleep 0.2
  done
  echo ". Success!"
}
```

By executing the command separately:
**docker exec singlestore-kafka memsql -e "select 1"**
obtained the following error:
**ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)**

In the same command, attempted to pass the root password param, but with no success, having the same exact error:
**docker exec singlestore-kafka memsql -u root -p "$ROOT_PASSWORD" -e "select 1"**

From the SingleStore Studio, can't seem to find any issues, and can login:
![2021-02-05_19-05-23](https://user-images.githubusercontent.com/7582777/107077948-7d29df80-67e5-11eb-83f2-a457fa2721ce.png)

Any further ideas? 

PS: If you wish so, in the end I can perform a PR.

**Comment by blinov-ivan** [comment]
Hi @FourElements ,
Thank you for this finding, seems like we missed checking this script before the last update.
We retested it with your suggested fixes and seems it works well now.
Here's the [commit](https://github.com/memsql/singlestore-kafka-connector/commit/2cb7e78bf8a15658a68814f0db08e6bdb436b301)
Thank you again for your time and efforts!

**Comment by FourElements** [comment]
I will just leave a suggestion and an observation.
For the suggestion, I would open port 8080 as well so that the user has easy access to the SingleStore Studio.
As for the observation, I tested and everything worked smoothly, but could stop to notice this behavior (screenshot attached)
![2021-02-05_19-05-23](https://user-images.githubusercontent.com/7582777/107275061-2c1a2580-6a49-11eb-90c9-9014b4852563.png)
As you can see, the same id appears 10 times, meaning I can only assume the expected loop beeing executed in the script _ingest-data.sh_ is not working as intended:
```
for i in {1..10}
do
  docker run \
    --net=confluent \
    --rm \
    -e CLASSPATH=/usr/share/java/monitoring-interceptors/monitoring-interceptors-5.0.0.jar \
    --mount type=bind,source="$(pwd)"/demo/data/songs.json,target=/opt/songs.json \
    confluentinc/cp-kafka-connect:5.0.0 \
    bash -c 'cat /opt/songs.json | kafka-console-producer --request-required-acks 1 --broker-list kafka:9092 --topic singlestore_json_songs --producer-property interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor --producer-property acks=1' >/dev/null 2>/dev/null
    echo "Data produced. $i of 10"
done
```
That would be all :)
